[1]
name = "Assembly"
source_file = "main.asm"
compiler_cmd = "nasmld"
compiler_args = ["-f", "elf64", "main.asm"]
run_cmd = "./a.out"
check_args = ["-v"]
comment = ";"

[2]
name = "Bash"
source_file = "script.sh"
run_cmd = "bash"
run_args = ["script.sh"]
check_args = ["--version"]
comment = "#"

[3]
cf_id = 43
name = "C (GCC)"
source_file = "main.c"
compiler_cmd = "gcc"
compiler_args = ["-fmax-errors=10", "-lm", "-Wall", "-O2", "main.c"]
run_cmd = "./a.out"
check_args = ["--version"]
comment = "//"

[4]
cf_id = 91
name = "C++ (GCC)"
source_file = "main.cpp"
compiler_cmd = "g++"
compiler_args = ["-fmax-errors=10", "-lm", "-Wall", "-O2", "main.cpp"]
run_cmd = "./a.out"
check_args = ["--version"]
comment = "//"

[5]
cf_id = 9
name = "C# (Mono)"
source_file = "Main.cs"
compiler_cmd = "mcs"
compiler_args = ["Main.cs"]
run_cmd = "mono Main.exe"
check_args = ["-V"]
comment = "//"

[6]
name = "SBCL"
source_file = "script.lisp"
run_cmd = "sbcl"
run_args = ["--script", "script.lisp"]
check_args = ["--version"]
comment = ";"

[7]
cf_id = 28
name = "D (DMD)"
source_file = "main.d"
compiler_cmd = "dmd"
compiler_args = ["main.d"]
run_cmd = "./main"
check_args = ["--version"]
comment = "//"

[8]
name = "Elixir"
source_file = "script.exs"
run_cmd = "elixir"
run_args = ["script.exs"]
check_args = ["--version"]
comment = "#"

[9]
name = "Erlang/OTP 27"
source_file = "main.erl"
run_cmd = "escript"
run_args = ["main.erl"]
check_args = ["--version"]
comment = "#"

[10]
name = "Fortran (Gfortran)"
source_file = "main.f90"
compiler_cmd = "gfortran"
compiler_args = ["main.f90"]
run_cmd = "./a.out"
check_args = ["--version"]
comment = "//"

[11]
cf_id = 32
name = "Go"
source_file = "main.go"
compiler_cmd = "go"
compiler_args = ["build", "main.go"]
run_cmd = "./main"
run_cmd_win = "./main.exe"
check_args = ["version"]
comment = "//"

[12]
cf_id = 12
name = "Haskell (GHC)"
source_file = "main.hs"
compiler_cmd = "ghc"
compiler_args = ["main.hs"]
run_cmd = "./main"
run_cmd_win = "./main.exe"
check_args = ["--version"]
comment = "--"

[13]
cf_id = 87
name = "Java"
source_file = "Main.java"
compiler_cmd = "javac"
compiler_args = ["Main.java"]
run_cmd = "java"
run_args = ["Main"]
check_args = ["--version"]
comment = "//"

[14]
cf_id = 55
name = "Javascript (Nodejs)"
source_file = "script.js"
compiler_cmd = "node"
compiler_args = ["-c", "script.js"]
run_cmd = "node"
run_args = ["script.js"]
check_args = ["--version"]
comment = "//"

[15]
name = "Lua"
source_file = "script.lua"
compiler_cmd = "lua"
compiler_args = ["script.lua"]
run_cmd = "lua"
run_args = ["./luac.out"]
check_args = ["-v"]
comment = "--"

[16]
cf_id = 19
name = "Ocaml"
source_file = "main.ml"
compiler_cmd = "ocamlc"
compiler_args = ["main.ml"]
run_cmd = "./a.out"
check_args = ["--version"]

[17]
name = "Octave"
source_file = "script.m"
run_cmd = "octave-cli"
run_args = ["-q", "--no-gui", "--no-history", "script.m"]
check_args = ["--version"]
comment = "//"

[18]
cf_id = 4
name = "Pascal (FPC)"
source_file = "main.pas"
compiler_cmd = "fpc"
compiler_args = ["main.pas"]
run_cmd = "./main"
run_cmd_win = "./main.exe"
check_args = ["-iW"]
comment = "//"

[19]
cf_id = 6
name = "PHP"
source_file = "script.php"
run_cmd = "php"
run_args = ["script.php"]
check_args = ["-v"]
comment = "//"

[20]
cf_id = 31
name = "Python"
source_file = "script.py"
compiler_cmd = "python3"
compiler_args = ["-m", "py_compile", "script.py"]
run_cmd = "python3"
run_args = ["script.py"]
check_args = ["--version"]
comment = "#"

[21]
cf_id = 67
name = "Ruby"
source_file = "script.rb"
compiler_cmd = "ruby"
compiler_args = ["-c", "script.rb"]
run_cmd = "ruby"
run_args = ["script.rb"]
check_args = ["--version"]
comment = "#"

[22]
cf_id = 75
name = "Rust"
source_file = "main.rs"
compiler_cmd = "rustc"
compiler_args = ["-O", "main.rs"]
run_cmd = "./main"
run_cmd_win = "./main.exe"
check_args = ["-V"]
comment = "//"

[23]
name = "Typescript"
source_file = "script.ts"
compiler_cmd = "tsc"
compiler_args = ["script.ts"]
run_cmd = "node"
run_args = ["script.js"]
check_args = ["--version"]
comment = "//"

[24]
cf_id = 43
name = "C (Clang)"
source_file = "main.c"
compiler_cmd = "clang"
compiler_args = ["-O2", "main.c"]
run_cmd = "./a.out"
check_args = ["--version"]
comment = "//"

[25]
cf_id = 89
name = "C++ (Clang)"
source_file = "main.cpp"
compiler_cmd = "clang++"
compiler_args = ["-O2", "main.cpp"]
run_cmd = "./a.out"
check_args = ["--version"]
comment = "//"

[26]
cf_id = 88
name = "Kotlin"
source_file = "Main.kt"
compiler_cmd = "kotlinc"
compiler_args = ["Main.kt"]
run_cmd = "kotlin"
run_args = ["MainKT"]
check_args = ["-version"]
comment = "//"

[27]
name = "R"
source_file = "script.r"
run_cmd = "Rscript"
run_args = ["script.r"]
check_args = ["--version"]
comment = "//"

[28]
cf_id = 20
name = "Scala"
source_file = "Main.scala"
compiler_cmd = "scalac"
compiler_args = ["Main.scala"]
run_cmd = "scala"
run_args = ["Main"]
check_args = ["--version"]
comment = "//"

[29]
name = "Visual Basic.Net (vbnc)"
source_file = "Main.vb"
compiler_cmd = "vbnc"
compiler_args = ["Main.vb"]
run_cmd = "mono"
run_args = ["Main.exe"]
check_args = ["-V"]
comment = "//"

[30]
cf_id = 13
name = "Perl"
source_file = "script.pl"
run_cmd = "perl"
run_args = ["script.pl"]
check_args = ["--version"]
comment = "//"

[31]
name = "Clojure"
source_file = "main.clj"
run_cmd = "clojure"
run_args = ["-M", "main.clj"]
check_args = ["--version"]
comment = "//"

[32]
name = "F#"
source_file = "script.fsx"
run_cmd = "dotnet"
run_args = ["fsi", "script.fsx"]
check_args = ["--version"]
comment = "//"

[33]
name = "Groovy"
source_file = "script.groovy"
compiler_cmd = "groovyc"
compiler_args = ["script.groovy"]
run_cmd = "groovy"
run_args = ["script"]
check_args = ["--version"]
comment = "//"
